---
title: "今日からできる再現可能な論文執筆"
author: 
  - "国里愛彦(専修大学)"
  - "竹林由武(福島県立医科大学)"
date: '2020年10月31日'
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: xaringan-themer.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
extra_css <- list(
  ".red"   = list(color = "red"),
  ".green"   = list(color = "green"),
  ".small" = list("font-size" = "60%"),
  ".med" = list("font-size" = "80%"),
  ".full-width" = list(
    display = "flex",
    width   = "100%",
    flex    = "1 1 auto"
  )
)
style_mono_accent(base_color = "#006400",
  text_font_size = "30px",
  code_font_size = "20px",
  padding = "1em 1em 1em 1em",#margin
  header_h1_font_size = "45px",
  header_h2_font_size = "40px",
  header_h3_font_size = "35px",
  header_color = "#006400",
  header_font_google = google_font("Song Myung"),
  text_font_google   = google_font("Song Myung", "400", "400i"),
  code_font_google   = google_font("Song Myung"),
  link_color = "#A52A2A",
  extra_css = extra_css
)
```

<!-- 
0.事前に環境構築のドキュメントを送る（dockerとローカル） 国里
1.再現可能な解析や論文執筆とは？（コピペダメゼッタイ）10分　国里
2.RStudioとRmarkdown(さらにはTeX)環境を整える（0の内容について，WinとMacの実演動画を流す，解説，Q&A）10分　国里
3.Rmarkdownで論文を書いてみよう！raticleパッケージのテンプレートで簡単に体験してもらう(パッケージの概要とまずはKnitして感動を共有する，あとはTipsを)。30分　竹林さん
4.日本語論文を書いてみよう！30分　国里<TWS用サイトを作る>
5.スライドも本もウェブサイトも作れるぞ！！！10分　竹林さん
-->

---
# 1.再現可能な解析や論文執筆とは？

---
# 2.RStudioとRmarkdown環境を整える


---
# 4.Rmarkdownで日本語論文を書いてみよう！

 